modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
    modId="improvedpets"
    version="${file.jarVersion}"
    displayName="Improved pets"
    logoFile="improvedpets.png"
    credits="Thanks for download the mod"
    authors="Pyotcho https://github.com/pyotcho"
    description=''''''
[[dependencies.improvedpets]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.improvedpets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"